### ISSUE TITLE
Warning message from nf_qc

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/nextflow_pipelines#10]
```
$ nf_qc barcode*fastq.gz
N E X T F L O W  ~  version 20.01.0
Launching `/bi/apps/nextflow/nextflow_pipelines/nf_qc` [big_mercator] - revision: b0b701e699
WARN: DSL 2 IS AN EXPERIMENTAL FEATURE UNDER DEVELOPMENT -- SYNTAX MAY CHANGE IN FUTURE RELEASE
WARN: There's no process matching config selector: TRIM_GALORE
```

**Comment by FelixKrueger** [comment]
These warnings come from the `withName` directives in the `nextflow.config`, or rather when the process is not used, e.g.:

```
  withName: TRIM_GALORE{
       cpus = 4
       memory = 10.GB
        // module 
    }
```

I suppose we could move also move this elsewhere, e.g. inside `trim_galore.mod.nf`

**Comment by FelixKrueger** [comment]
The `withName` directives produce a WARN statement whenever that process is not used in a workflow. If one doesn't want that, we could use the `withLabel` directive instead.

I have now taken out the `withName` directives, and replaced them with `withLabel` or with dynamic retry statements handling resources with the module files instead.
