### ISSUE TITLE
MultiQC report on rnaseq pipeline gets default name

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/nextflow_pipelines#37]
On nf_rnaseq the multiqc report is just called multiqc_report.html rather than having a name which reflects the basename of the files being processed.

I thought this was fixed in the BSSeq pipelines so I'm not sure why it's not being picked up here.  We can probably work out out though.

**Comment by FelixKrueger** [comment]
We added the option `--prefix PREFIX` that would be picked up by MultiQC. For the automated pipelines (`analyse_run_folder`), this is being extracted from the filenames automatically (see [here](https://github.com/s-andrews/illuminaprocessing/commit/b1bdd326b7b9c7ba9f305deb57826675b294f2c5)).

**Comment by s-andrews** [comment]
I guess that would do it :-)
