### ISSUE TITLE
Requirement for this pipeline?

### ISSUE THREAD

**Issue by ShouWenWang** [s-andrews/nextflow_pipelines#39]
Hi, Simon
        I talked to Richard about scNMT-seq data analysis, and he pointed me to your nextflow pipeline. I wonder what are the dependencies that I would need to install to run it in a different cluster, like the clusters in Harvard that I am using now. It use the SLURM schedule system?

  Shou-Wen Wang
Harvard Postdoc

**Comment by s-andrews** [comment]
Nextflow can talk to a number of different scheduler systems.  We also use slurm on ours and it works very well.

The only other thing you'd need to get this to work out of the box would be to have environment modules for all of the software packages used, and to set up the genome configuration for the genome assembly you want to use.
