### ISSUE TITLE
Trim galore is unnecessarily slow and doesn't parallelise

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/nextflow_pipelines#43]
Trimming is currently the rate limiting step in our processing pipelines.  I think we can improve this in a couple of ways.

1. We don't currently use parallelisation but trim_galore supports this directly with ```-j``` so that's an easy fix.
2. We're doing default compression which we know is fairly slow, we can probably reduce the compression level (cutadapt has an option for this) to get basically the same output with less CPU load.

**Comment by FelixKrueger** [comment]
just quickly chiming in here, using `igzp` for decompression and `pigz` for compression should help a lot. And yes, `-j` too. (https://github.com/FelixKrueger/TrimGalore/releases/tag/0.6.8)

**Comment by s-andrews** [comment]
Just tried it.  It does :-)

**Comment by s-andrews** [comment]
Fixed in [675f4f2](https://github.com/s-andrews/nextflow_pipelines/commit/675f4f2f385ed19bd8a7a1466433c133b6f9ca14)
